# Generated by Django 3.1.14 on 2024-07-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='dateToApply',
            new_name='lastDateToApply',
        ),
    ]
