# Generated by Django 5.0.6 on 2024-06-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default='Default School Name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='principal',
            field=models.CharField(default='Default Principal', max_length=50),
            preserve_default=False,
        ),
    ]
