# Generated by Django 5.0.6 on 2024-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_school_name_school_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(default='default Location', max_length=50),
            preserve_default=False,
        ),
    ]
