# Generated by Django 5.0.6 on 2024-06-11 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_school_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(default='18'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default='13293', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app1.school'),
            preserve_default=False,
        ),
    ]
